export type Meeting = {
  id: number
  title: string
  type: '온라인' | '오프라인'
  category: string
  location: string
  date: string
  time: string
  participants: string
  currentCount: number
  maxCount: number
  host: string
  hostAvatar: string
  description: string
  tags: string[]
}

export const MEETINGS: Meeting[] = [
  {
    id: 1,
    title: '자기 전 힐링 뜨개',
    type: '온라인',
    category: '온라인 모임',
    location: '온라인 (Zoom)',
    date: '11/19 (화)',
    time: '오후 8:00',
    participants: '10명 참여',
    currentCount: 10,
    maxCount: 20,
    host: '뜨개마녀',
    hostAvatar: '#C9956C',
    description: '하루의 마무리를 뜨개와 함께 해요. 자기 전 1시간, 편안한 공간에서 함께 뜨개질하며 힐링해요. 초보자도 환영합니다!',
    tags: ['온라인', '힐링', '저녁', '초보환영'],
  },
  {
    id: 2,
    title: '요뜨: 뜨개 요가',
    type: '오프라인',
    category: '오프라인 모임',
    location: '성북구',
    date: '11/19 (화)',
    time: '오후 8:00',
    participants: '3자리 남음 · 진행 확정',
    currentCount: 7,
    maxCount: 10,
    host: '요가뜨개',
    hostAvatar: '#E07B4F',
    description: '뜨개와 요가를 결합한 힐링 모임이에요. 요가로 몸을 풀고 뜨개로 마음을 정리해요.',
    tags: ['오프라인', '요가', '힐링', '성북구'],
  },
  {
    id: 3,
    title: 'CGV 뜨개 상영회',
    type: '오프라인',
    category: '주말 모임',
    location: '마포구',
    date: '11/16 (일)',
    time: '오후 5:00',
    participants: '25명 참석중',
    currentCount: 25,
    maxCount: 30,
    host: '영화뜨개',
    hostAvatar: '#A0785A',
    description: '영화를 보면서 뜨개를 해요! 조용한 핸드크래프트 상영회입니다.',
    tags: ['오프라인', '주말', '영화', '마포구'],
  },
  {
    id: 4,
    title: '차와 함께 뜨뜨 🍵',
    type: '오프라인',
    category: '평일 모임',
    location: '종로구',
    date: '11/18 (화)',
    time: '오후 2:00',
    participants: '3자리 남음',
    currentCount: 7,
    maxCount: 10,
    host: '차뜨개',
    hostAvatar: '#D4A373',
    description: '종로의 아늑한 차집에서 함께 뜨개해요. 다양한 차와 함께하는 오후 뜨개 모임이에요.',
    tags: ['오프라인', '평일', '카페', '종로구'],
  },
  {
    id: 5,
    title: '주말 소모임 뜨개 클럽',
    type: '오프라인',
    category: '소규모 모임',
    location: '강남구',
    date: '11/22 (토)',
    time: '오전 11:00',
    participants: '1자리 남음',
    currentCount: 4,
    maxCount: 5,
    host: '소모임장',
    hostAvatar: '#B5838D',
    description: '소수 정예로 진행하는 뜨개 클럽. 5명 이하의 아늑한 모임이에요.',
    tags: ['오프라인', '소규모', '주말', '강남구'],
  },
  {
    id: 6,
    title: '뜨개 마켓 단체 참가',
    type: '오프라인',
    category: '대규모 모임',
    location: '서울 전역',
    date: '11/23 (일)',
    time: '오전 10:00',
    participants: '42명 참여',
    currentCount: 42,
    maxCount: 100,
    host: '마켓뜨개',
    hostAvatar: '#6B9080',
    description: '핸드메이드 마켓에 함께 참가해요. 판매자와 방문자 모두 환영!',
    tags: ['오프라인', '대규모', '마켓', '주말'],
  },
  {
    id: 7,
    title: '홍대 앞 동네 뜨개방',
    type: '오프라인',
    category: '동네 모임',
    location: '마포구 홍대',
    date: '11/20 (목)',
    time: '오후 7:00',
    participants: '8명 참여',
    currentCount: 8,
    maxCount: 15,
    host: '홍대니터',
    hostAvatar: '#E76F51',
    description: '홍대 근처 사시는 분들 모여요! 동네에서 편하게 뜨개해요.',
    tags: ['오프라인', '동네', '홍대', '마포구'],
  },
  {
    id: 8,
    title: '뜨개 원데이 클래스',
    type: '오프라인',
    category: '뜨개 원데이',
    location: '성동구',
    date: '11/21 (금)',
    time: '오후 1:00',
    participants: '5자리 남음',
    currentCount: 5,
    maxCount: 10,
    host: '원데이강사',
    hostAvatar: '#8B9D77',
    description: '하루만에 작은 작품을 완성하는 원데이 클래스에요. 실과 도구는 모두 제공됩니다.',
    tags: ['오프라인', '원데이', '클래스', '성동구'],
  },
]
